name: osint_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  file_picker: ^11.0.3
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  google_fonts: ^8.1.0
  http: ^1.6.0
  latlong2: ^0.10.1
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
