SERVICES = {
    "GitHub" : {"url" : "https://github.com/{}", "error_marker" : "not found"},
    "Telegram" : {"url" : "https://t.me/{}","error_marker" : "if you have"},
    "TikTok" : {"url" : "https://www.tiktok.com/@{}","error_marker" : "couldn't find this account"},
    "Reddit": {"url": "https://www.reddit.com/user/{}","error_marker": "banned"},
    "Steam": {"url": "https://steamcommunity.com/id/{}","error_marker": "could not be found"},
    "SoundCloud": {"url": "https://soundcloud.com/{}","error_marker": "can’t find that user"},
    "Basecamp": {"url": "https://{}.basecamp.com","error_marker": "launchpad"},
    "Habr": {"url": "https://habr.com/ru/users/{}/","error_marker": "page not found"},
    "VKontakte": {"url": "https://vk.com/{}", "error_marker": "page not found"},
    "Tumblr": {"url": "https://{}.tumblr.com", "error_marker": "not found"},
    "Pinterest": {"url": "https://www.pinterest.com/{}/", "error_marker": "not found"},
    "Flickr": {"url": "https://www.flickr.com/people/{}/", "error_marker": "not found"},
    "Imgur": {"url": "https://imgur.com/user/{}", "error_marker": "zoinks! you've taken a wrong turn"},
    "GitLab": {"url": "https://gitlab.com/{}", "error_marker": "page not found"},
    "CodePen": {"url": "https://codepen.io/{}", "error_marker": "404"},
    "Replit": {"url": "https://replit.com/@{}", "error_marker": "404"},
    "Pastebin": {"url": "https://pastebin.com/u/{}", "error_marker": "not found"},
    "HackerRank": {"url": "https://www.hackerrank.com/{}", "error_marker": "page not found"},
    "LeetCode": {"url": "https://leetcode.com/{}/", "error_marker": "not found"},
    "Codeforces": {"url": "https://codeforces.com/profile/{}", "error_marker": "not found"},
    "Kaggle": {"url": "https://www.kaggle.com/{}", "error_marker": "not found"},
    "TryHackMe": {"url": "https://tryhackme.com/p/{}", "error_marker": "not found"},
    "Behance": {"url": "https://www.behance.net/{}", "error_marker": "oops! we can’t find that page"},
    "Dribbble": {"url": "https://dribbble.com/{}", "error_marker": "whoops, that page is gone"},
    "Fiverr": {"url": "https://www.fiverr.com/{}", "error_marker": "page not found"},
    "Upwork": {"url": "https://www.upwork.com/freelancers/~{}", "error_marker": "page not found"},
    "Spotify": {"url": "https://open.spotify.com/user/{}", "error_marker": "page not found"},
    "Twitch": {"url": "https://m.twitch.tv/{}", "error_marker": "content is unavailable"},
    "Vimeo": {"url": "https://vimeo.com/{}", "error_marker": "not found"},
    "Bandcamp": {"url": "https://bandcamp.com/{}", "error_marker": "not found"},
    "Xbox": {"url": "https://xboxgamertag.com/search/{}", "error_marker": "not found"},
    "PlayStation": {"url": "https://psnprofiles.com/{}", "error_marker": "not found"},
    "Roblox": {"url": "https://www.roblox.com/user.aspx?username={}", "error_marker": "page cannot be found"},
    "Chess.com": {"url": "https://www.chess.com/member/{}", "error_marker": "member not found"},
    "Lichess": {"url": "https://lichess.org/@/{}", "error_marker": "page not found"},
    "Medium": {"url": "https://medium.com/@{}", "error_marker": "out of nothing, something"},
    "Dev.to": {"url": "https://dev.to/{}", "error_marker": "this page does not exist"},
    "Blogger": {"url": "https://{}.blogspot.com", "error_marker": "not found"},
    "WordPress": {"url": "https://{}.wordpress.com", "error_marker": "doesn’t exist"},
    "Goodreads": {"url": "https://www.goodreads.com/{}", "error_marker": "page not found"},
    "Wattpad": {"url": "https://www.wattpad.com/user/{}", "error_marker": "user not found"},
    "MyAnimeList": {"url": "https://myanimelist.net/profile/{}", "error_marker": "invalid name"},
    "Patreon": {"url": "https://www.patreon.com/{}", "error_marker": "not found"},
    "Linktree": {"url": "https://linktr.ee/{}", "error_marker": "page not found"},
    "About.me": {"url": "https://about.me/{}", "error_marker": "page not found"},
    "Gravatar": {"url": "https://en.gravatar.com/{}", "error_marker": "not found"},
    "AllMyLinks": {"url": "https://allmylinks.com/{}", "error_marker": "page not found"},
    "TripAdvisor": {"url": "https://www.tripadvisor.com/Profile/{}", "error_marker": "not found"},
    "Wikipedia": {"url": "https://en.wikipedia.org/wiki/User:{}", "error_marker": "wikipedia does not have a user page with this exact name"},
    "HackerOne": {"url": "https://hackerone.com/{}", "error_marker": "page not found"},
    "Bugcrowd": {"url": "https://bugcrowd.com/{}", "error_marker": "not found"},
    "Keybase": {"url": "https://keybase.io/{}", "error_marker": "not found"},
    "Duolingo": {"url": "https://www.duolingo.com/profile/{}", "error_marker": "not found"},
    "Codecademy": {"url": "https://www.codecademy.com/profiles/{}", "error_marker": "not found"},
    "FreeCodeCamp": {"url": "https://www.freecodecamp.org/{}", "error_marker": "we couldn't find"},
    "HackerNews": {"url": "https://news.ycombinator.com/user?id={}", "error_marker": "no such user"},
    "ProductHunt": {"url": "https://www.producthunt.com/@{}", "error_marker": "not found"},
    "Disqus": {"url": "https://disqus.com/by/{}/", "error_marker": "not found"},
    "Lobsters": {"url": "https://lobste.rs/u/{}", "error_marker": "not found"},
    "Hashnode": {"url": "https://hashnode.com/@{}", "error_marker": "not found"},
    "Bitbucket": {"url": "https://bitbucket.org/{}/", "error_marker": "not found"},
    "Gitee": {"url": "https://gitee.com/{}", "error_marker": "not found"},
    "NPM": {"url": "https://www.npmjs.com/~{}", "error_marker": "not found"},
    "PyPI": {"url": "https://pypi.org/user/{}/", "error_marker": "not found"},
    "SourceForge": {"url": "https://sourceforge.net/u/{}/profile/", "error_marker": "not found"},
    "Gitea": {"url": "https://gitea.com/{}", "error_marker": "not found"},
    "Unsplash": {"url": "https://unsplash.com/@{}", "error_marker": "not found"},
    "Pexels": {"url": "https://www.pexels.com/@{}", "error_marker": "not found"},
    "Pixabay": {"url": "https://pixabay.com/users/{}", "error_marker": "not found"},
    "Giphy": {"url": "https://giphy.com/channel/{}", "error_marker": "not found"},
    "Tenor": {"url": "https://tenor.com/users/{}", "error_marker": "not found"},
    "Dailymotion": {"url": "https://www.dailymotion.com/{}", "error_marker": "not found"},
    "Canva": {"url": "https://www.canva.com/{}", "error_marker": "not found"},
    "Letterboxd": {"url": "https://letterboxd.com/{}/", "error_marker": "not found"},
    "Last.fm": {"url": "https://www.last.fm/user/{}", "error_marker": "not found"},
    "Mixcloud": {"url": "https://www.mixcloud.com/{}/", "error_marker": "not found"},
    "Speedrun": {"url": "https://www.speedrun.com/user/{}", "error_marker": "not found"},
    "Kongregate": {"url": "https://www.kongregate.com/accounts/{}", "error_marker": "not found"},
    "Newgrounds": {"url": "https://{}.newgrounds.com/", "error_marker": "not found"},
    "IGN": {"url": "https://www.ign.com/person/{}", "error_marker": "not found"},
    "MySpace": {"url": "https://myspace.com/{}", "error_marker": "not found"},
    "Untappd": {"url": "https://untappd.com/user/{}", "error_marker": "not found"},
    "TradingView": {"url": "https://www.tradingview.com/u/{}/", "error_marker": "not found"},
    "BuyMeACoffee": {"url": "https://www.buymeacoffee.com/{}", "error_marker": "not found"},
    "Ko-fi": {"url": "https://ko-fi.com/{}", "error_marker": "not found"},
    "Gumroad": {"url": "https://{}.gumroad.com/", "error_marker": "not found"},
    "Kickstarter": {"url": "https://www.kickstarter.com/profile/{}", "error_marker": "not found"},
    "Indiegogo": {"url": "https://www.indiegogo.com/individuals/{}", "error_marker": "not found"},
    "Trello": {"url": "https://trello.com/{}", "error_marker": "page not found"},
    "Scratch": {"url": "https://scratch.mit.edu/users/{}/", "error_marker": "not found"},
    "SlideShare": {"url": "https://www.slideshare.net/{}", "error_marker": "not found"},
    "Instructables": {"url": "https://www.instructables.com/member/{}/", "error_marker": "not found"},
    "HubPages": {"url": "https://hubpages.com/@{}", "error_marker": "not found"},
    "Flipboard": {"url": "https://flipboard.com/@{}", "error_marker": "not found"},
    "Strava": {"url": "https://www.strava.com/athletes/{}", "error_marker": "not found"},
    "Foursquare": {"url": "https://foursquare.com/{}", "error_marker": "not found"},
    "Fandom": {"url": "https://www.fandom.com/u/{}", "error_marker": "not found"},
    "Rumble": {"url": "https://rumble.com/user/{}", "error_marker": "not found"},
    "Pastee": {"url": "https://paste.ee/u/{}", "error_marker": "not found"}
}

EMAIL_SERVICES = {
    "Adobe": {
        "url": "https://auth.services.adobe.com/signin/v1/account/check",
        "method": "POST",
        "payload_template": {
            "username": "{}" 
        },
        "error_marker": "username_not_found"
    },
    # Наша новая, легальная и послушная цель
    "LeakCheck Public": {
        "url": "https://leakcheck.io/api/public?check={}",
        "method": "GET",  # ВНИМАНИЕ: тут метод GET!
        "payload_template": {}, # Для GET запроса тело пустое
        "error_marker": "not found" # Если API ответит ошибкой
    },
    "XposedOrNot": {
        "url": "https://api.xposedornot.com/v1/check-email/{}",
        "method": "GET",
        "payload_template": {},
        # Если почты нет в базах, этот сервис возвращает 404 статус, 
        # но мы застрахуем себя текстовым маркером
        "error_marker": "error" 
    }
}